### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by guanjuwei** [Owen-Liuyuxuan/papers_reading_sharing.github.io#1]
您好,请问下这个论文的数据集在哪可以下载的到？谢谢！

**Comment by Owen-Liuyuxuan** [comment]
请问一下是什么数据集? 你问的是KITTI吗?

**Comment by guanjuwei** [comment]
A Convolutional Network for Joint Deraining and Dehazing from A Single Image for Autonomous Driving in Rain这个同时加了雾和雨的数据集。

**Comment by Owen-Liuyuxuan** [comment]
那个我也没有找到，paper里面没有，也没有搜到作者主页。

**Comment by guanjuwei** [comment]
我看了下这篇论文被引为0，可能代码，数据集都没公布。谢谢您！
